### ISSUE TITLE
I can't download math books

### ISSUE THREAD

**Issue by VoltrY** [creeperkafasi/isler-kutuphane#1] opened 2024-10-14 14:11 UTC

**Comment by creeperkafasi** [comment] 2024-10-15 21:43
Could you provide more information on the steps to replicate your issue? It works fine for me. Make sure to follow the steps in the disclaimer if you are using a Chromium based browser.

**Comment by VoltrY** [comment] 2024-10-16 09:36
I am using firefox browser. and when I press the math option of the site, no books appear.

**Comment by creeperkafasi** [comment] 2024-10-16 12:24
Closing as cannot reproduce.

**Closed as completed by creeperkafasi** 2024-10-16 12:24 UTC
